# Generated by Django 3.1.3 on 2020-11-17 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import formapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'M'), (1, 'F')], null=True)),
                ('weight', models.PositiveSmallIntegerField(null=True)),
                ('height', models.PositiveSmallIntegerField(null=True)),
                ('country', models.CharField(max_length=70, null=True)),
                ('state', models.CharField(max_length=70, null=True)),
                ('city', models.CharField(max_length=70, null=True)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(0, 'Tester'), (1, 'Loader')])),
                ('load_resul', models.BooleanField(null=True)),
                ('test_result', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='UserAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cough', models.FileField(blank=True, null=True, upload_to='audio/cough/', validators=[formapp.models.size_limit])),
                ('phrase', models.FileField(blank=True, null=True, upload_to='audio/phrase/', validators=[formapp.models.size_limit])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.userdata', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Have_or_had_fever', models.BooleanField()),
                ('Have_or_had_a_cough', models.BooleanField()),
                ('Have_or_had_catarrh', models.BooleanField()),
                ('feel_or_felt_weak', models.BooleanField()),
                ('feel_or_felt_pain', models.BooleanField()),
                ('Have_or_had_stomatc_pain', models.BooleanField()),
                ('Have_or_had_headache', models.BooleanField()),
                ('Have_or_had_lost_smell', models.BooleanField()),
                ('Have_or_had_lost_taste', models.BooleanField()),
                ('Have_or_had_sore_throat', models.BooleanField()),
                ('Have_or_had_problem_breathing', models.BooleanField()),
                ('Have_or_had_pain_chest', models.BooleanField()),
                ('Have_or_had_dizziness', models.BooleanField()),
                ('Have_or_had_movement_problem', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.userdata', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smoker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke_status', models.PositiveIntegerField(choices=[(0, 'I dont Smoke'), (1, 'Ocasionally'), (2, '1-10 cigarretes per day'), (3, '11-20 cigarretes per day'), (4, '>21 cigarretes per day'), (5, 'I was but not anymore')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.userdata', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.PositiveIntegerField(choices=[(0, '-O'), (1, '+O'), (2, '-A'), (3, '+A'), (4, '-B'), (5, '+B'), (6, '-AB'), (7, '+AB')], null=True)),
                ('is_transplant_patient', models.BooleanField(default=False, null=True)),
                ('is_pregnant', models.BooleanField(default=False, null=True)),
                ('Feeding_baby_breast_milk', models.BooleanField(default=False, null=True)),
                ('oncology_patient', models.BooleanField(default=False, null=True)),
                ('vih_positive', models.BooleanField(default=False, null=True)),
                ('heart_problems', models.BooleanField(default=False, null=True)),
                ('asma', models.BooleanField(default=False, null=True)),
                ('any_lung_disease', models.BooleanField(default=False, null=True)),
                ('diabete', models.BooleanField(default=False, null=True)),
                ('kidney_failure', models.BooleanField(default=False, null=True)),
                ('liver_disease', models.BooleanField(default=False, null=True)),
                ('have_any_immune_system_disease', models.BooleanField(default=False, null=True)),
                ('hypertension', models.BooleanField(default=False, null=True)),
                ('overweight', models.BooleanField(default=False, null=True)),
                ('have_any_metabolic_disease', models.BooleanField(default=False, null=True)),
                ('has_any_neurological_disease', models.BooleanField(default=False, null=True)),
                ('have_kidney_disease', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.userdata', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_regularly_public_tranportation', models.PositiveIntegerField(choices=[(0, 'Bus'), (1, 'Taxi'), (2, 'Uber'), (3, 'Lyft'), (4, 'Train'), (5, 'Metro'), (6, 'Public Bycicle'), (7, 'None'), (8, 'Other')], null=True)),
                ('go_shopping_regularly', models.BooleanField(default=False, null=True)),
                ('how_expose_on_work', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('lately_went_to_hospital', models.BooleanField(default=False, null=True)),
                ('had_contact_with_person_that_have_covid_symptoms', models.BooleanField(default=False, null=True)),
                ('use_daily_mask_and_disinfectant', models.BooleanField(default=False, null=True)),
                ('live_or_work_in_an_area_of_spread_or_contagion', models.BooleanField(default=False, null=True)),
                ('activity_more_than_10', models.BooleanField(default=False, null=True)),
                ('face_to_face_Service_on_home', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.userdata', unique=True)),
            ],
        ),
    ]
