# Generated by Django 3.1.3 on 2020-11-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20201117_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='load_resul',
            new_name='load_result',
        ),
    ]
