# Generated by Django 3.1.3 on 2020-11-19 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_auto_20201119_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='how_expose_on_work',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
