# Generated by Django 3.1.3 on 2020-11-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0010_auto_20201119_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='did_covid_test',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='when_covid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
