# Generated by Django 3.1.3 on 2020-11-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_auto_20201123_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='formapp.userdata'),
        ),
    ]
