# Generated by Django 3.1.3 on 2020-11-27 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0012_auto_20201127_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='formapp.userdata'),
        ),
    ]
