# Generated by Django 3.1.3 on 2020-11-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_auto_20201127_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='reject',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
