# Generated by Django 3.1.3 on 2020-12-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0015_auto_20201128_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='use_regularly_public_tranportation',
            field=models.PositiveIntegerField(choices=[(0, 'No lo utilizo'), (1, 'servicio de bus, metro o similares'), (2, 'servicio de taxi, uber o similares')], null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='reject',
            field=models.PositiveIntegerField(choices=[(0, 'REJETED'), (1, 'ACCEPTED'), (2, 'PENDING')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tester'), (0, 'Loader')]),
        ),
    ]
