# Generated by Django 3.1.3 on 2020-12-08 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0016_auto_20201202_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraudio',
            old_name='phrase',
            new_name='phrase1',
        ),
    ]
