# Generated by Django 3.1.3 on 2020-12-08 00:39

from django.db import migrations, models
import formapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0017_auto_20201207_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraudio',
            name='phrase2',
            field=models.FileField(blank=True, null=True, upload_to='audio/phrase/', validators=[formapp.models.size_limit]),
        ),
        migrations.AddField(
            model_name='useraudio',
            name='phrase3',
            field=models.FileField(blank=True, null=True, upload_to='audio/phrase/', validators=[formapp.models.size_limit]),
        ),
    ]
